extends:
  - eslint:recommended
  - airbnb
  - airbnb-typescript
  - next/core-web-vitals

parserOptions:
  project: tsconfig.json

ignorePatterns:
  - '*.config.js'

rules:
  array-element-newline: [error, consistent]
  array-bracket-newline: [error, consistent]
  jsx-quotes: [error, prefer-single]
  no-console: 0
  no-alert: 0
  react/jsx-props-no-spreading: 0
  react/button-has-type: 0
  react/destructuring-assignment: 0
  react-hooks/exhaustive-deps: 0
  jsx-a11y/label-has-associated-control:
    - error
    - required:
        some: [nesting, id]
